CREATE TABLE "radio" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ime" varchar,
  "frekvenca" float,
  "channel" varchar,
  "valid_until" date,
  "phone" varchar,
  "email" varchar,
  "kraj_id" integer
);

CREATE TABLE "drzave" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ime" varchar,
  "koda" varchar
);

CREATE TABLE "kraj" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ime" varchar,
  "postna_st" varchar,
  "drzava_id" integer
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "email" varchar,
  "phone" varchar,
  "kraj_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "comment_text" text,
  "frequency_id" integer,
  "user_id" integer,
  "created_at" timestamp
);

ALTER TABLE "radio" ADD FOREIGN KEY ("kraj_id") REFERENCES "kraj" ("id");

ALTER TABLE "drzave" ADD FOREIGN KEY ("id") REFERENCES "kraj" ("drzava_id");

ALTER TABLE "users" ADD FOREIGN KEY ("kraj_id") REFERENCES "kraj" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("frequency_id") REFERENCES "radio" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

